### ISSUE TITLE
Add versioning to the wCCD example front-end

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-browser-wallet#210]
**Task description**
It would be easier to maintain the running wCCD front-end and its docker images if we have clear versioning of the wCCD example project.

**Sub-tasks**
- [ ] Add versioning to the wCCD example project
- [ ] Add versioning to the docker image
- [ ] Add versioning to be displayed at the front-end
