### ISSUE TITLE
Add a fullscreen view button

### ISSUE THREAD

**Issue by orhoj** [Concordium/concordium-browser-wallet#439]
**Task description**

Some users have requested a button to open the browser wallet in a tab instead of as the extension popup. This task will a button to the settings page that will open such a tab. The fullscreen view will not contain any custom views of the wallet, and will just be a centered version of what is currently shown in the extension popup. This can then later be extended to e.g. include a fullscreen onboarding flow if needed.

**Sub-tasks**

- [x] Add button to open fullscreen view of the browser wallet.
- [x] Make modifications to the CSS so that the fullscreen view is centered.
- [x] Make modifications to the CSS to ensure that nothing is broken in the fullscreen view (menu dropdowns do not work out of the box when making the fullscreen view).
